apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-gps-jamming
  namespace: prd-cm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: vehicle-gps-jamming
  template:
    metadata:
      labels:
        app: vehicle-gps-jamming
    spec:
      containers:
        - name: vehicle-gps-jamming
          image: ghcr.io/kirapixel/cm-vehicle-gps-jamming:20260210220340
          envFrom:
            - secretRef:
                name: flask-cm-spectr-secret
