apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluentbit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name   tail
        Path   /var/log/containers/*.log
        Parser docker_short
        Tag    kube.*

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Merge_Log_Key       log
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Kube_URL            https://kubernetes.default.svc:443

    [OUTPUT]
        Name                 gelf
        Match                *
        Host                 logs.cm.lk-sp.ru
        Port                 12201
        Mode                 udp
        Gelf_Short_Message_Key log
        Gelf_Full_Message_Key  log
        Gelf_Host_Key          kubernetes.pod_name
        Gelf_Level_Key         level
        Gelf_Timestamp_Key     time

  parsers.conf: |
    [PARSER]
        Name   docker_short
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Decode_Field_As   escaped   log
