apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-operator
  namespace: prd-cm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: virtual-operator
  template:
    metadata:
      labels:
        app: virtual-operator
    spec:
      containers:
        - name: virtual-operator
          image: ghcr.io/kirapixel/cm-virtual-operator:20260111142639
          envFrom:
            - secretRef:
                name: flask-cm-spectr-secret
