apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-cashing
  namespace: prd-cm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: db-cashing
  template:
    metadata:
      labels:
        app: db-cashing
    spec:
      containers:
        - name: db-cashing
          image: ghcr.io/kirapixel/flask-db-cashing:20260216211601
          envFrom:
            - secretRef:
                name: flask-cm-spectr-secret
