apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-api-gateway
  namespace: prd-cp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: cp-api-gateway
  template:
    metadata:
      labels:
        app: cp-api-gateway
    spec:
      containers:
        - name: cp-api-gateway
          image: ghcr.io/kirapixel/cp-api-gateway:20251116143152
          ports:
            - containerPort: 31499
          envFrom:
            - secretRef:
                name: flask-cm-spectr-secret
